#!/bin/bash


##### Handle Notebooks #####
# TODO: skip this part if no notebooks, or if jupyter not available
# TODO: handle stupid filenames -- convert to lowercase, eliminate spaces

NOTEBOOK_DIR='content/notebooks'

# manually convert notebooks to html
NOTEBOOKS=${NOTEBOOK_DIR}/*.ipynb
for NB in ${NOTEBOOKS}
do
  HTML_FN=`basename ${NB} .ipynb`.html
  if [ ! -f ${NB} ]; then
    echo "Converting ${NB} to html..."
    jupyter nbconvert -y --to html ${NB}
  fi
done


##### Pelican Site Generation #####

make html
echo Starting server on http://localhost:8000/
# google-chrome http://localhost:8000/index.html &
make serve
